name: Build Project

on:
  push:
    branches: [ "**" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x] 

    steps:
      
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Install dependencies
      working-directory: 'Aya''s Portfolio version 02'
      run: npm ci

    - name: Build application
      working-directory: 'Aya''s Portfolio version 02'
      run: npm run build --if-present
